[project]
name = "bedrock-using-litellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm[proxy]>=1.79.0",
    "python-dotenv>=1.2.1",
    "traceloop-sdk==0.51.1",
]
